### ISSUE TITLE
Client Error with Cloning Block

### ISSUE THREAD

**Issue by superstorm192** [manicdigger/manicdigger#203]
I have reproduced an error using these steps:

1) get on a creative server? (I couldn't reproduce this error on my survival server)
`Maybe it happens when you literally have 0 blocks (creative mode infinite blocks)?`

2) scroll middle mouse to an empty activematerial slot (no blocks are placed there)
`Maybe it happens because of there being Null blocks in that specific activematerial slot?`

3) look at a block that is not in your activematerial slot (like you are going to take the block)
`The activematerial becomes the block that matches in the activematerial bar?`

4) hold down middle mouse such the clone sound sounds more than one time.
`Maybe it happens because of too much stuff happening in a short amount of time?`

5) watch in horror as an annoying error message disconnects you saying "Your client threw an exception at server."
`Really? Now i have to fight an invisible mouse pointer to find and click the dreaded [OKAY] button so I can return to the server select screen and rejoin the server that i so rudely got disconnected from by an annoying mouse button that is hard to NOT hold down for longer than the time it takes to make the second "Hey, im being middle mouse clicked still, have some more food my little computer."`

**Comment by croxxx** [comment]
Thank you for the thorough report. I could reproduce the issue easily.
- Current release (2015-02-17): Game crashes as reported
- Latest GIT code (2015-08-22): No crash on a local test server could be achieved
- Client compiled from latest GIT on creative release server: Worked fine for 30s, then crashed

Could you try reproducing this with latest code from here: https://github.com/manicdigger/manicdigger-builds/blob/gh-pages/ManicDiggerLatestBinary.zip

**Comment by superstorm192** [comment]
I only tried it once on the server, the issue doesn't seem to be happening on the unreleased version, however i cannot connect to my "indev" sever a second time using the current release of manic digger, however works fine using the manic digger launcher provided in the unreleased build.

Exception Details:
```
8/23/2015 5:09:49 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Game.ProcessPacket(Packet_Server packet)
   at ProcessPacketTask.Run()
   at TaskScheduler.Update(Game game, Single dt)
   at ScreenGame.Render(Single dt)
   at MainMenu.DrawScene(Single dt)
   at MainMenu.OnNewFrame(NewFrameEventArgs args)
   at MainMenuNewFrameHandler.OnNewFrame(NewFrameEventArgs args)
   at GamePlatformNative.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.OnRenderFrame(FrameEventArgs e)
   at OpenTK.GameWindow.OnRenderFrameInternal(FrameEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Stopwatch render_watch, Double& next_render, FrameEventArgs render_args)
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at OpenTK.GameWindow.Run()
   at ManicDiggerProgram.Start(String[] args)
   at ManicDiggerProgram.<ManicDiggerProgram>c__AnonStorey0.<>m__0()
   at ManicDigger.ClientNative.CrashReporter.Start(ThreadStart start)
```

**Comment by croxxx** [comment]
This still happens in latest version.
This is what the server console outputs:
```
Exception at client 2. Disconnecting client.
Message to all: &7Player &0croxxx&f &7disconnected.
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
  at System.Collections.Generic.Dictionary`2[ManicDigger.ProtoPoint,ManicDigger.Item].get_Item (ManicDigger.ProtoPoint key) [0x00000] in <filename unknown>:0 
  at InventoryServer.WearItem (Packet_InventoryPosition from, Packet_InventoryPosition to) [0x00000] in <filename unknown>:0 
  at Server.DoCommandInventory (Int32 player_id, Packet_ClientInventoryAction cmd) [0x00000] in <filename unknown>:0 
  at Server.TryReadPacket (Int32 clientid, System.Byte[] data) [0x00000] in <filename unknown>:0 
  at Server.ProcessNetMessage (NetIncomingMessage msg, NetServer mainSocket, System.Diagnostics.Stopwatch s) [0x00000] in <filename unknown>:0 
```

Seems like a serverside inventory handling bug to me.
