### ISSUE TITLE
SQLiteException: Library used incorrectly

### ISSUE THREAD

**Issue by superstorm192** [manicdigger/manicdigger#223]
using my map mod, i am encountering this error message frequently on unloaded chunks. on a later pass, there are no error messages. **Is there a function to check if a block is in a loaded chunk or not?** It would make the mod simpler and not have to force load chunks if it is not completely necessary to do so.
```
System.Data.SQLite.SQLiteException: Library used incorrectly
No transaction is active on this connection
   at System.Data.SQLite.SQLiteTransaction.IsValid(Boolean throwError)
   at System.Data.SQLite.SQLiteTransaction.Commit()
   at ChunkDbSqlite.SetChunks(IEnumerable`1 chunks)
   at ChunkDbCompressed.SetChunks(IEnumerable`1 chunks)
   at ChunkDb.SetChunk(IChunkDb db, Int32 x, Int32 y, Int32 z, Byte[] c)
   at ServerSystemUnloadUnusedChunks.Update(Server server, Single dt)
   at Server.Process()
```

This is an error message generated using `m.GetBlock(x, y, z);` on an 'unused chunk' and it is even inside a `try{} catch{}` so appearently the error is NOT caused by the `m.GetBlock(x,y,z);` directly.

**Comment by croxxx** [comment]
Currently there is no possibility to check if a certain chunk is loaded.
Also the force-loading by accessing a block in a currently not loaded chunk causes issues and is to be removed at some point.

When that happens there will be new methods exposed that allow checking, loading and maybe even unloading chunks manually.
