### ISSUE TITLE
Guns, Third Person, and ERROR!

### ISSUE THREAD

**Issue by superstorm192** [manicdigger/manicdigger#240]
When in third person, and facing in the sky, and shooting any kind of gun (grenades also), your entire Manic Digger Window gets closed and an error popup appears.

![image](https://cloud.githubusercontent.com/assets/10588108/12218794/205f7a6e-b6ef-11e5-84c8-36c636282722.png)

Upon consulting said file, I find this error:

```
-------------------------------
1/9/2016 4:26:54 PM: Critical error occurred
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at BlockOctreeSearcher.SearchPrivate(PredicateBox3D query, Box3D box)
   at BlockOctreeSearcher.Search(PredicateBox3D query)
   at BlockOctreeSearcher.LineIntersection(DelegateIsBlockEmpty isEmpty, DelegateGetBlockHeight getBlockHeight, Line3D line, IntRef retCount)
   at Game.Pick(BlockOctreeSearcher s_, Line3D line, IntRef retCount)
   at ModPicking.NextBullet(Game game, Int32 bulletsshot)
   at ModPicking.UpdatePicking(Game game)
   at ModPicking.OnMouseUp(Game game, MouseEventArgs args)
   at Game.MouseUp(MouseEventArgs args)
   at ScreenGame.OnMouseUp(MouseEventArgs e)
   at MainMenu.HandleMouseUp(MouseEventArgs e)
   at MainMenuMouseEventHandler.OnMouseUp(MouseEventArgs e)
   at GamePlatformNative.Mouse_ButtonUp(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.NativeWindow.OnMouseUp(MouseButtonEventArgs e)
   at OpenTK.NativeWindow.OnMouseUpInternal(Object sender, MouseButtonEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.NativeWindowBase.OnMouseUp(MouseButton button)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at OpenTK.GameWindow.Run()
   at ManicDiggerProgram.Start(String[] args)
   at ManicDiggerProgram.<ManicDiggerProgram>c__AnonStorey0.<>m__0()
   at ManicDigger.ClientNative.CrashReporter.Start(ThreadStart start)
-------------------------------
```

**Comment by lgthibault** [comment]
Could not repro with latest build.

Switched mod to War (in current.txt file). Shot upwards in the sky with rifle, then grenade.
Went to every corner of the map and did the same. Would not crash.

Would you provide some more specifics about your setup? Perhaps zip your game folder so I can repro that?

Thanks!

**Comment by joshi1999** [comment]
Were you in the Third Person Mode? (F5)

**Comment by lgthibault** [comment]
I was in first person mode.

**Comment by joshi1999** [comment]
The crash is in the third person mode

**Comment by joshi1999** [comment]
Press ingame f5 to be in the third person mode

**Comment by croxxx** [comment]
Using both current release and latest code I could not reproduce the issue.
